<a href="https://colab.research.google.com/github/AshwinRaikar88/dive2dl/blob/tensorflow/Notebooks/2.1_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()

# Data Manipulation 

A tensor represents a (possibly multi-dimensional) array of numerical values. 


* With *one axis* (K=1), a tensor is called a **Vector**. 

* With *two axes* (K=2), a tensor is called a **Matrix**. 

* With *K > 2 axes*, we drop the specialized names and just refer to the object as a **Kth order tensor**.

## tf.range()

The range(n) function, creates a vector of evenly spaced values, starting at 0 (included) and ending at n (not included). By Default the step size (Delta) is 1.Unless otherwise specified, New tensors are stored in main memory and designated for CPU-based computation.

In [ ]:
x = tf.range(12, dtype=tf.float32)
x # x is a vector with 12 elements

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

In [ ]:
x = tf.range(12, delta=2, dtype=tf.float32)
x # we will have 6 elements (Note that 12 is excluded)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 0.,  2.,  4.,  6.,  8., 10.], dtype=float32)>

In [ ]:
x = tf.range(start=1, limit=13, delta=1, dtype=tf.float32)
x # we will have 12 elements starting from 1 to 12

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
      dtype=float32)>

Each of these values is called an element of the tensor. The tensor x contains 12 elements. We can inspect the total number of elements in a tensor via the size function.

In [ ]:
x.shape

TensorShape([12])

## tf.reshape()

We can change the shape of a tensor without altering its size or values, by invoking reshape. For example, we can transform our vector x whose shape is (12,) to a matrix X with shape (3, 4). This new tensor retains all elements but reconfigures them into a matrix. Notice that the elements of our vector are laid out one row at a time and thus x[3] == X[0, 3].

In [ ]:
X = tf.reshape(x, (3, 4))
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)>

In [ ]:
# Notice that the elements of our vector are laid out one row at a time and thus x[3] == X[0, 3]
x[3] == X[0][3]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

Note that specifying every shape component to reshape is redundant. Because we already know our tensor’s size, we can work out one component of the shape given the rest. 

For example, given a tensor of size  and target shape (, ), we know that . To automatically infer one component of the shape, we can place a -1 for the shape component that should be inferred automatically. In our case, instead of calling x.reshape(3, 4), we could have equivalently called x.reshape(-1, 4) or x.reshape(3, -1).

In [ ]:
x.reshape(3, -1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)>

In [ ]:
x.reshape(-1, 4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)>